BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "CarParking" (
	"CID"	INTEGER,
	"AID"	INTEGER,
	"StartTime"	DATETIME NOT NULL,
	"EndTime"	DATETIME NOT NULL,
	"Cost"	FLOAT NOT NULL,
	"MaxPricePerDay"	FLOAT NOT NULL,
	CONSTRAINT "pa_fk" FOREIGN KEY("AID","MaxPricePerDay") REFERENCES "ParkingArea"("AID","MaxPricePerDay") ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT "check_car_parking_dates" CHECK(EndTime>=StartTime),
	CONSTRAINT "check_car_parking_cost" CHECK(MaxPricePerDay>=Cost),
	FOREIGN KEY("CID") REFERENCES "Car"("CID") ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY("CID","AID","StartTime")
);
CREATE TABLE IF NOT EXISTS "Car" (
	"CID"	INTEGER,
	"CellPhoneNumber"	VARCHAR(11) NOT NULL,
	"CreditCard"	VARCHAR(20) NOT NULL,
	"ExpirationDate"	VARCHAR(5) NOT NULL,
	"ThreeDigits"	VARCHAR(3) NOT NULL,
	"ID"	INTEGER,
	FOREIGN KEY("ID") REFERENCES "Resident"("RID") ON UPDATE CASCADE ON DELETE RESTRICT,
	PRIMARY KEY("CID")
);
CREATE TABLE IF NOT EXISTS "ParkingArea" (
	"AID"	INTEGER,
	"Name"	VARCHAR(30) NOT NULL UNIQUE,
	"NID"	INTEGER,
	"PricePerHour"	FLOAT NOT NULL,
	"MaxPricePerDay"	FLOAT NOT NULL,
	FOREIGN KEY("NID") REFERENCES "Neighborhood"("NID") ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY("AID")
);
CREATE TABLE IF NOT EXISTS "TrashCanResident" (
	"TCID"	INTEGER,
	"RID"	INTEGER,
	PRIMARY KEY("TCID","RID"),
	FOREIGN KEY("RID") REFERENCES "Resident"("RID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TCID") REFERENCES "TrashCan"("TCID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "TrashCan" (
	"TCID"	INTEGER,
	"CreationDate"	DATETIME NOT NULL,
	"ExpirationDate"	DATETIME NOT NULL,
	CONSTRAINT "check_creation_expiration_date" CHECK(ExpirationDate>CreationDate),
	PRIMARY KEY("TCID")
);
CREATE TABLE IF NOT EXISTS "ApartmentResident" (
	"RID"	INTEGER,
	"StreetName"	VARCHAR(50),
	"Number"	INTEGER,
	"Door"	INTEGER,
	CONSTRAINT "fk_apartment" FOREIGN KEY("StreetName","Number","Door") REFERENCES "Apartment"("StreetName","Number","Door") ON UPDATE CASCADE ON DELETE RESTRICT,
	PRIMARY KEY("RID","StreetName","Number","Door"),
	FOREIGN KEY("RID") REFERENCES "Resident"("RID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Resident" (
	"RID"	INTEGER,
	"FirstName"	VARCHAR(50) NOT NULL,
	"LastName"	VARCHAR(50) NOT NULL,
	"BirthDate"	DATETIME NOT NULL,
	PRIMARY KEY("RID")
);
CREATE TABLE IF NOT EXISTS "Apartment" (
	"StreetName"	VARCHAR(50),
	"Number"	INTEGER,
	"Door"	INTEGER,
	"Type"	VARCHAR(30) NOT NULL,
	"NID"	INTEGER,
	"SizeSquareMeter"	INTEGER CHECK(SizeSquareMeter>=0),
	PRIMARY KEY("StreetName","Number","Door"),
	FOREIGN KEY("NID") REFERENCES "Neighborhood"("NID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "ProjectConstructorEmployee" (
	"PID"	INTEGER,
	"EID"	INTEGER,
	"StartWorkingDate"	DATETIME,
	"EndWorkingDate"	DATETIME,
	"JobDescription"	VARCHAR(30),
	FOREIGN KEY("PID") REFERENCES "Project"("PID") ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT "check_start_end_working_date" CHECK(EndWorkingDate>=StartWorkingDate),
	FOREIGN KEY("EID") REFERENCES "ConstructorEmployee"("EID") ON UPDATE CASCADE ON DELETE RESTRICT,
	PRIMARY KEY("PID","EID")
);
CREATE TABLE IF NOT EXISTS "Project" (
	"PID"	INTEGER,
	"Name"	VARCHAR(25) NOT NULL,
	"Description"	VARCHAR(50),
	"Budget"	FLOAT NOT NULL,
	"Neighborhood"	INTEGER,
	FOREIGN KEY("Neighborhood") REFERENCES "Neighborhood"("NID") ON UPDATE CASCADE ON DELETE RESTRICT,
	PRIMARY KEY("PID")
);
CREATE TABLE IF NOT EXISTS "Neighborhood" (
	"NID"	INTEGER,
	"Name"	VARCHAR(50) NOT NULL,
	PRIMARY KEY("NID")
);
CREATE TABLE IF NOT EXISTS "ConstructorEmployee" (
	"EID"	INTEGER,
	"CompanyName"	VARCHAR(25) NOT NULL,
	"SalaryPerDay"	INTEGER NOT NULL,
	PRIMARY KEY("EID"),
	FOREIGN KEY("EID") REFERENCES "Employee"("EID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Department" (
	"DID"	INTEGER,
	"Name"	VARCHAR(50) NOT NULL UNIQUE,
	"Description"	VARCHAR(50),
	"ManagerID"	INTEGER,
	FOREIGN KEY("ManagerID") REFERENCES "OfficialEmployee"("EID") ON UPDATE CASCADE ON DELETE RESTRICT,
	PRIMARY KEY("DID")
);
CREATE TABLE IF NOT EXISTS "OfficialEmployee" (
	"EID"	INTEGER,
	"StartWorkingDate"	DATETIME,
	"Degree"	VARCHAR(25),
	"Department"	INTEGER,
	FOREIGN KEY("Department") REFERENCES "Department"("DID") ON UPDATE CASCADE ON DELETE RESTRICT,
	PRIMARY KEY("EID"),
	FOREIGN KEY("EID") REFERENCES "Employee"("EID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "CellPhone" (
	"EID"	INTEGER,
	"Number"	VARCHAR(11),
	PRIMARY KEY("EID","Number"),
	FOREIGN KEY("EID") REFERENCES "Employee"("EID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Employee" (
	"EID"	INTEGER,
	"FirstName"	VARCHAR(25) NOT NULL,
	"LastName"	VARCHAR(25) NOT NULL,
	"BirthDate"	DATETIME,
	"Door"	INTEGER,
	"Number"	INTEGER NOT NULL,
	"StreetName"	VARCHAR(50) NOT NULL,
	"City"	VARCHAR(25) NOT NULL,
	PRIMARY KEY("EID")
);
COMMIT;
